version: '3.8'

services:
  food_forward_app:
    build:
      context: ./frontend/food_forward_app
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Adjust the port mapping as neede d for your Flutter app
    depends_on:
      - emulator
      - food_forward_backend

  emulator:
      image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
      expose:
         - 8554/tcp
         - 5555/tcp
      devices:
         - '/dev/kvm:/dev/kvm'


  food_forward_backend:
    build:
      context: ./backend/WebServiceApplication # Update this path to your backend directory
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    
