name: food_forward_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.18.0
  shared_preferences: ^2.0.16
  flutter_secure_storage: ^9.0.0


  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

